#!/usr/bin/env micropython
from ev3dev2.motor import *
from ev3dev2.sensor import *

from robot import *

bot = Robot(OUTPUT_A, OUTPUT_B, 56, 15, INPUT_1, INPUT_2,
            gyro_sensor_port=INPUT_3, motor1=LargeMotor(OUTPUT_C))

bot.gyro_sensor.reset()
time.sleep(0.05)
bot.gyro_straight(40, 20, 0.5)
print("goes straight out of home area")
bot.gyro_turn(39, 40, 26)
print("turns toward the plane transportation journey")
print(bot.last_gyro_angle, '  ', bot.gyro_sensor.angle)
bot.gyro_straight(40, 14, 0.35)
print("goes straight until in position to move plane")
bot.motor1.on_for_rotations(30, 0.46)
print("moves arm down and latches onto plane")
bot.gyro_turn(-50, 0, 60)
print("turns plane out of holder")
print(bot.last_gyro_angle, '  ', bot.gyro_sensor.angle)
bot.motor1.on_for_rotations(30, -0.45)
print("arm lifts of plane")
bot.gyro_turn(78, -20, -40)
print("turns robot away and then towards the truck")
print(bot.last_gyro_angle, '  ', bot.gyro_sensor.angle)
bot.gyro_straight(50, 42, 0.5)
print("moves straight towards truck")
bot.gyro_turn(-49, 0, 20)
print("turns into correct position for truck")
print(bot.last_gyro_angle, '  ', bot.gyro_sensor.angle)
bot.gyro_straight(40,1,0.5)
bot.motor1.on_for_rotations(30, 0.43)
print("lowers arm onto the truck")
bot.gyro_turn(-50.02, -3, 100)
print("turns truck out of holder")
print(bot.last_gyro_angle, '  ', bot.gyro_sensor.angle)
bot.motor1.on_for_rotations(-30, 0.5)
# bot.gyro_straight(-40, -20, 0.5)
bot.gyro_turn(-90 - bot.last_gyro_angle, -40, 0)
print(bot.last_gyro_angle, '  ', bot.gyro_sensor.angle)
bot.gyro_straight(-40, -25, 0.5)
bot.gyro_turn(90, 40, 0)
print(bot.last_gyro_angle, '  ', bot.gyro_sensor.angle)
bot.gyro_straight(40,15,0.5)
bot.gyro_turn(-80,0,40)
bot.stop_on_black(7, 40)
bot.gyro_straight(20, 8, 0.5)
